plugins:
  ballotage_enabled:
    default: false
    client: true
  ballotage_voting_group:
    default: ""
    type: group
  ballotage_oversight_group:
    default: ""
    type: group
  ballotage_oversight_can_manage:
    default: false
  ballotage_info_text:
    default: ""
    textarea: true
  ballotage_timezone:
    default: ""
    type: enum
    enum: "Ballotage::TimezoneEnum"
    client: true
